### ISSUE TITLE
Mention the pandocfilters dependency in the README

### ISSUE THREAD

**Issue by nigef** [pyta-uoft/website#18]
.. since the build process requires the `pandocfilters` module

**Comment by david-yz-liu** [comment]
@nigef this is a great thing to do. Can you please add this?

**Comment by nigef** [comment]
waiting to hear from @hayleyZHL and @shweta97 about their experience trying to build the website with the pandocfilters dependency.

**Comment by nigef** [comment]
[PR 26](https://github.com/pyta-uoft/website/pull/26)
