### ISSUE TITLE
Add a navigation bar to the website

### ISSUE THREAD

**Issue by david-yz-liu** [pyta-uoft/website#22]
@Jasminewwwu, why don't you work on this? It will likely take some time to get the styling right, but it's a nice task to work on.

**Comment by nigef** [comment]
#### requirements:
- links to section categories, and links to message headings.
- responsive design (probably mobile-first, even though not as common use case).
- fixed position (left side is standard)
- button to show/hide the navigation, i.e. toggle.

#### future enhancements (if needed, can be implemented by other people):
- distinguish in the navigation bar: the current section and title of example that's on the screen, for link clicked. Maybe also: update the link style as page is scrolled. ([Example: scroll and watch nav update with your location](http://expressjs.com/en/api.html#app.engine), or [another similar example](http://docs.meteor.com/api/accounts.html#Meteor-users)
- other UI/UX enhancements...
