### ISSUE TITLE
Fix formatting issues

### ISSUE THREAD

**Issue by shweta97** [pyta-uoft/website#29]
Make the heading format of each message uniform and add missing semi-colons like line #547 in index.md.

**Comment by david-yz-liu** [comment]
@shweta97 it would be good to link to a specific line number where you noticed this problem, so that it's clearer what you mean.

**Comment by shweta97** [comment]
@david-yz-liu there are more than ten lines where I noticed this and hence didn't want to mention them here.

**Comment by david-yz-liu** [comment]
You should link to one as an example.

**Comment by david-yz-liu** [comment]
Fixed in #30.
